### ISSUE TITLE
Responsive beyond 1280px?

### ISSUE THREAD

**Issue by mfarfanr** [mfarfanr/kari#1]
Responsive Design (RWD) doesn't just mean creating a desktop version and making the same source work in smaller devices. RWD also means bigger devices. 

I would recommend to use a background image that fades in into a background color that can cover 100% of the browser's width, otherwise the website will look like it is not really responsive. Using 1280px as a max-width defeats the RWD purpose.

![issue](https://cloud.githubusercontent.com/assets/1386491/14236377/67cd0f34-f9e2-11e5-8575-3124b66eb1d7.png)

**Comment by amyhayes** [comment]
I agree that the goal is to fill the whole space regardless of the design.  Can you show me your suggestion as I understand but cannot visualize it. Thanks

**Comment by mfarfanr** [comment]
Hi Amy, yes, I will show you what I mean later today. Thanks.

**Comment by mfarfanr** [comment]
Amy,

Please go [here](http://www.maneli.net/kari/src/project/docs/templates/home.html) and then resize your browser. **Chrome** is what I use to test initial development but I guess you can use IE or Firefox, etc.

This is not a finished product but you can see what I am talking about. If you resize the browser (or you open the URL using your phone or tablet) you will probably see that the image used as a background is stretched/shrunk but always keeping its proper width and height (image is not distorted). When the browser's viewport (width) gets smaller, the image resizes responsively but to the point where the height is no longer enough to cover the entire viewport as you can see below.

![image](https://cloud.githubusercontent.com/assets/1386491/14372595/0fa39a22-fd10-11e5-992a-c4679f7dc938.png)

This can be solved many different ways... some ok some not so elegant per say... but I would start by recommending to **not** use a background image like this unless you want to provide either one huge image that will 90% ensure you will never face the situation shown above... or... you will give me many different images I can use for each *breakpoint* you want to support. When I say *breakpoint*, I mean how many browser viewport sizes you want to support (i.e. mobile, tablet and desktop). Viewport is the part of the browser window that actually contains the web page (browser's window size minus toolbars, borders, scrollbars, etc.) Usually for a site like yours it is common to support **3** breakpoints. The way the content is styled in the 3 breakpoints will change to fit properly in each of those breakpoints... for example, the mobile breakpoint will go from 1 pixel to 480 pixels. The tablet will go from 481 pixels to 768 pixels. Desktop will be > 768 pixels.

I have many recommendations as to what is best (in terms of design and performance, industry standards, etc.) and I can guide you if you want - but in terms of using background images to cover for the entire viewport - you can as long as they are fully responsive... from a small mobile phone to a huge 29" monitor... etc. but the truth is not many people do it this way because of many reasons - mostly because it is not practical for the reasons depicted on the screen shot above, also because huge images will mean huge number of bytes and slower performances when loading the website pages. Also, when doing responsive websites, simplicity is a must... If you think about it... it is recommended that you use a mobile-first approach, meaning you design for phones first... so that your content becomes clean and you decide then what is really important for you to display to your customers. If you start the other way around (i.e. the desktop view) and you start putting a lot of content, when you go "down" to mobile you will find yourself wondering what to do with all the content and what to hide so that mobile looks clean. At that point in time, some of your business users or customers will **not** be happy that you're taking away their content especially because you're leaving other content from other departments and how dare you, etc. :smile: This mobile-first approach applies to all content, from images to verbiage to data in tables, everything!

Anyway, if you have some time, you can look at how [Microsoft](https://www.microsoft.com/en-us/) does it... or [Boston Globe](http://www.bostonglobe.com/) or many other responsive websites from lead companies. You can load their websites and resize them using your browser and see how the content shifts/changes.

I can continue but I will stop now so you can think about some of these things and let us know what you think and how you would like to proceed.

Thanks. M

**Comment by amyhayes** [comment]
M,  
I understand what you are saying but am not sure how to best proceed.  The goal is to ensure that viewing the home page from any device gives a professional impression.  Based on what you say then we need to have 3 breakpoints.  What would it cost to have you do this adjustment or do I take it back to the design company?  I am not sure which is most expedient and cost effective.

-A

**Comment by mfarfanr** [comment]
Hi Amy,

I understand.

In terms of breakpoints, yes, three breakpoints is OK. It will be tricky with the tables in the next pages, but I have worked with them before in different ways so when it comes to those I can tell you what options you have... but generally it is either removing columns from tables or just displaying the data top-bottom in blocks (one block per row). For example:

```
  Col 1 | Col 2   | Col 3   | Col 4      | Col 5
--------+---------+---------+------------+--------
    088 | John    | Smith   |   1,234.00 | Closed
    091 | Jane    | Doe     |      42.00 | Active
``` 
will turn into:
```
Col 1:   088
Col 2:   John
Col 3:   Smith
Col 4:   1,234.00
Col 5:   Closed

Col 1:   091
Col 2:   John
Col 3:   Smith
Col 4:   42.00
Col 5:   Closed
```
Anyway, in terms of the look-n-feel, I can suggest you a couple of things and you can tell me what you want to do, and I will make it work and/or ask for the things I need to do it.

- I would ask you to reconsider using a **full** background image. I understand you want to look professional but the trend for a couple of years now is simplicity for *these types* of websites. Less is more... why? Because making content responsive needs to follow a mobile-first approach as I explained. But don't get me wrong... you can add nice pictures to your website, including a nice logo, good fonts and colors, a couple nice call-to-action buttons (for Login and Iniciar sesion), etc. Also, simplicity makes content load faster, especially in mobile phones where processors are not that powerful. If you want to keep a full background image, that's fine, but I just want to let you it is not the best practice nor the norm these days. If you want to go with that though, I will probably ask for different sizes to fit each breakpoint.
- I need to know your colors, or color palette. This depends of course on the previous item, your logo, etc. A good tool to pick colors and how they match is [this](https://coolors.co/app/008000-621331-463f3a-8a817c-bcb8b1) website.

I guess I need those two things for now, and then I can work on this first landing page and then continue into the inner pages. If you want me to quickly show you a slightly different approach by providing some examples, I can do that too.

I am sorry it is a little hard to explain all this... but I just want to make sure I am trying to give you my experience so you can make better decisions that fit your goals but I also understand you want to reduce expenses...

Let me know if you want to go with your initial design, or if you want to explore something slightly different but keeping your main initial idea. I am **NOT** a designer but I do understand what works best in terms of usability (user-friendliness) and I know how eyes move across pages, how people scan pages, etc. 

M

**Comment by amyhayes** [comment]
Manolo,

Thank you for your detailed reply.   I believe that the request has gotten off track in that we are looking only to improve the view for the “Home Page” or landing page as the pages that follow are a tool used by our producers and are not ‘public’.  What we need to improve is the impression given to anyone that looks for us on the www.  The current landing page is dated, too small and needs upgrading.  We are seeking for the landing page to be “responsive” and then that opened the conversation about making the rest of the site responsive for a user who accesses the information via a smaller device.  Given you suggested it, I asked for a quote to know what it might cost.    I appreciate you are putting in time to respond and consider changes but need to return to the task at hand.

We had a design company produce the new graphic and now we need it to be “loaded” or to replace the old landing page.  I agree with you that it needs to be responsive but I am not seeking to redo the colors or the back pages at this time.

Can you tell me if you can:

1.       Replace the old landing page with the new one provided by the design company

2.      Ensure that the new one is responsive and looks professional

3.      The cost to do 1 and 2

I really appreciate your (and Elizabeth’s) ongoing support!

Best,
Amy

**Comment by mfarfanr** [comment]
Ok Amy.

Thanks for the clarification.

We can proceed and work on (1 and 2) the way the home page mockup was initially submitted. We will get back to you on 3.

Thanks,
Manolo

**Comment by mfarfanr** [comment]
Amy,

Finishing 1 and 2 will probably require around 4 more hours. Most of the work is done but making sure all different breakpoints look OK require some testing. So far we have spent like 4 hours on it... so it will be 8 hours in total.

Manolo

**Comment by amyhayes** [comment]
Manolo,

Can you confirm the cost per hour please.

Thanks,
Amy

**Comment by mfarfanr** [comment]
*$65* an hour.

**Comment by amyhayes** [comment]
Thanks Manolo.  I want to be sure we are on the same page.   The goal is to improve just the landing page and its view ability to be sure it loads appropriately on a range of devices.

We have provided the “artwork” prepared by Emily of Jean Peterson and the tasking for you was to swap it out for the current landing page.  In this process, the issue of “scale” came into play as the current landing page does not fill the whole screen.   We are not redesigning any further pages at this time.

Please confirm we are in agreement given it is easy to lose the thread!

Best,
Amy

**Comment by mfarfanr** [comment]
Hi Amy. 

Yes... The task is to work on this **single** landing page to comply with your end goals, to make it:
- [x] Professional
- [x] Modern looking

... following the guidelines given in the initial artwork and this issue thread. We will use that initial set of images and if we have any questions as to how you would prefer the *background image* to show we will be asking you... but we will be working with what we have been given.

Manolo

**Comment by amyhayes** [comment]
Manolo

Hola.  Can you advise a likely time frame to complete this tasking.

Enjoy your weekend,
Amy

**Comment by mfarfanr** [comment]
Amy, it can be done during a weekend, like this one... or spread it out in a week... It's up to you. If you want this done asap, let us know. Or you want us to start the work, let us know... There is not a lot more to do besides a couple of changes, some cleanup and mostly testing.

**Comment by amyhayes** [comment]
Good morning. Yes, please do the work based on our exchanges to date- and the sooner the better.

Thanks!
Amy

**Comment by mfarfanr** [comment]
Will do.
