### ISSUE TITLE
Footer image

### ISSUE THREAD

**Issue by mfarfanr** [mfarfanr/kari#2]
Need a new footer image for the small logo on top of the address information. The psd in Fireworks doesn't open the file the right way. This is what I see:

![image](https://cloud.githubusercontent.com/assets/1386491/14236314/63e63c8e-f9e1-11e5-9813-717ce21d83a4.png)

I somewhat fixed it but I am not sure this is exactly what you need. Let us know.

**Comment by amyhayes** [comment]
Manuel,  I do not like the lighter green that is outlining the maroon in the logo box.  Can you make it the same color as the maroon or make it black?

**Comment by amyhayes** [comment]
M-
The footer on the second "issue" thread is as we had wanted it so I am assuming you resolved this problem.  If not, let me know.
-A

**Comment by mfarfanr** [comment]
OK. Thanks. If I need a new footer image for different breakpointsI will let you know.
